name: Chama Workflow compartilhado

on: 
  workflow_dispatch:
    inputs:
      nome-do-curso-enviado:
        required: true
        type: string
        description: 'chama workflow'

jobs:
  chama-workflow:
    uses: ./.github/workflows/trigger-workflow-call.yml
    with:
      nome-do-curso-recebido: ${{ inputs.nome-do-curso-enviado }}