name: Primeiro Wokflow

on:
  workflow_dispatch:

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Confere vers√£o do ubuntu
        run: cat /etc/os-release
      
      - name: Exibir uma mensagem
        run: echo "Fazendo curso de Github Actions"