name: Vendo arquivos compartilhados entre jobs

on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versão do ubuntu
        run: cat /etc/os-release
      
      - name: Exibir uma mensagem
        run: echo "Fazendo curso de Github Actions" > ${{ github.workspace }}/mensagem.txt

      - uses: actions/upload-artifact@v4
        with:
          name: strigus
          path: ${{ github.workspace }}/mensagem.txt

      - name: Outra coisa
        run: ls -lha

      - name: Ler conteúdo do arquivo
        run:  cat mensagem.txt
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: Listar arquivos
        run: ls -lha
        
      - uses: actions/download-artifact@v5
        with:
          name: strigus
          path: mensagem.txt
      - name: Ver o conteutdo do diretorio
        run: ls -lha && ls ./strigus/   
      - name: Mover arquivo
        run: mv strigus/mensagem.txt . && rm -rf ./strigus

      - name: Listar arquivos
        run: ls -lha
        
      - name: Acessa arquivo mensagem
        run: cat mensagem.txt