name: Trigger schedule

on:
  schedule:
    - cron: '14 18 * * 1'
jobs:
  job-schedule:
    runs-on: ubuntu-latest
    steps:

      - name: Printa schedule
        run: echo "job triggado por schedule, agora s√£o $(date) UTC"