name: Trigger discussion

on:
  discussion:
    types: [created, edited, answered]

jobs:
  job-discussion:
    runs-on: ubuntu-latest
    steps:

      - name: Printa discussion
        run: echo "job triggado por discussion"